### PR TITLE
UI development

### PR DESCRIPTION
**Pull request by Khaleb165**
implement menu items dialog
add hide keyboard function

### CODE REVIEW

**Comment by Mr-Ashitey** [comment]
Caleb, you didn't have to create a commit for all the "add hide keyboard function" implementation. They are all one. All though you implemented them in different files, you had to stage all as one under the same commit message.

**Comment by Mr-Ashitey** [comment]
Again your commit message is not so good. Your commit message must describe what you have done. It must not be vague but rather straight forward. 
So instead of "add hide keyboard function" you could have said this, "hide keyboard on textfield when tapped outside".

So you see this new commit message explains what you are doing (i.e. hide keyboard), where or what it is being used on (i.e. textfield) and the property or how it is done (i.e. the tap outside).

**Comment by Mr-Ashitey** [comment]
Have you checked out the camera thing?

**Comment by Khaleb165** [comment]
I'm on it. Will be done this evening

**Comment by Khaleb165** [comment]
Noted sir

**Pull request merged**
